### ISSUE TITLE
graphed date is incorrect

### ISSUE THREAD

**Issue by yasu-murata** [future-architect/gbilling-plot#1]
Image below is a capture of slack notification at 7/30.
So, the date of latest bar must be "07/30", but it's "07/05"
![image](https://user-images.githubusercontent.com/29366807/62093882-e3ab7480-b2b5-11e9-8b46-9d69f3dd8e12.png)

**Comment by ma91n** [comment]
Thank you @donkomura great works, this issue is solved.
